// apps/react-todo/src/routes/Home.jsx
import React from "react";
import PageHeader from "../lib/components/PageHeader";
import { Link } from "react-router-dom";
import styled from "styled-components";
import PlaceholderText from "../lib/components/PlaceholderText";
import Project from "../lib/components/Project";

const Home = ({ projects, todos }) => {
  return (
    <>
      <PageHeader
        title="Dina projekt"
        action={<Link to="/project">Skapa project</Link>}
      />
      {projects?.length > 0 ? (
        <ProjectsContainer>
          {projects.map((project) => (
            <Project
              project={project}
              key={project.id}
              todos={todos.filter((t) => t.projectId === project.id)}
            />
          ))}
        </ProjectsContainer>
      ) : (
        <PlaceholderText>Du har inga projekt än</PlaceholderText>
      )}
    </>
  );
};

const ProjectsContainer = styled.div`
  margin: 0 2rem;
  display: grid;
  grid-template-columns: repeat(auto-fill, minmax(33%, 1fr));
  gap: 1rem;
`;

export default Home;

// apps/svelte-spa-router-app/src/routes/Home.svelte
<script>
  import { link } from "svelte-spa-router";
  import Project from "../components/Project.svelte";
  import Header from "../components/PageHeader.svelte"
  import { projects } from "../stores";
</script>


<Header>
  <h2 slot="title">Dina projeket</h2>
  <a  slot="action" href="/project" use:link>Skapa Projekt</a> 
</Header>
{#if $projects.length > 0} 

<div class="projects">
  {#each $projects as project}
    <Project id={project.id} title={project.title} />
  {/each}
</div>
{:else}
  <p>Du har inga projekt än</p>
{/if}
<style>
  .projects {
    margin: 0 2rem;
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(33%, 1fr)); 
    gap: 1rem;
    
  }

  p {
    font-size: 1.2rem;
    font-weight: bold;
  }

</style>
