// apps/react-todo/src/routes/TodoDetail.jsx
import React, { useState, useEffect } from "react";
import { useParams, useNavigate } from "react-router-dom";
import Button from "../lib/components/Button";
import styled from "styled-components";

const TodoDetail = ({ todos, toggleTodo, deleteTodo }) => {
  let { id } = useParams();
  let navigate = useNavigate();
  const [todo, setTodo] = useState(todos.find((todo) => todo.id === id));

  useEffect(() => {
    setTodo(todos.find(todo => todo.id === id));
  }, [id, todos]);
  

  const handleToggle = (e) => toggleTodo(id);

  const handleDelete = (e) => {
    deleteTodo(id);
    navigate(-1);
    
  };

  if (!todo) return <></>;

  return (
    <>
      <h2>{todo.title}</h2>
      {todo.description && (
        <>
          <h3>Beskrivning</h3>
          <p>{todo.description}</p>
        </>
      )}
      <StyledDiv>
        <Button onClick={handleToggle} bgColor="#22D3EE">
          {todo.completed ? "Avmarkera" : "Makera som klar"}
        </Button>
        <Button onClick={handleDelete} bgColor="#ef4444">
          Ta bort uppgift
        </Button>
      </StyledDiv>
    </>
  );
};

  const StyledDiv = styled.div`
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  `; 

export default TodoDetail;

// apps/svelte-spa-router-app/src/routes/TodoDetail.svelte
<script>
  import { pop } from "svelte-spa-router";

  import Button from "../components/Button.svelte";
  import { todos } from "../stores";

  export let params = {};
  let id = params.id;
  $: todo = $todos.find((todo) => todo.id === id);

  const handleToggle = (e) => {
    todos.toggle(id);
    pop();
  };

  const handleDelete = (e) => {
    todos.remove(id);
    pop();
  };
</script>

{#if todo}
  <h2>{todo.title}</h2>
  {#if todo.description}
    <h3>Beskrivning</h3>
    <p>{todo.description}</p>
  {/if}
  <div>
    <Button on:click={handleToggle} --bg-color="#22D3EE">
      {#if todo.completed}Avmarkera
      {:else}
        Markera som klar
      {/if}
    </Button>
    <Button on:click={handleDelete} --bg-color="#ef4444">Ta bort uppgift</Button
    >
  </div>
{/if}

<style>
  div {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
  }
</style>
