// apps/react-todo/src/lib/components/Todo.jsx
import React from "react";
import styled from "styled-components";
import { useNavigate } from "react-router-dom";
import TodoCheckbox from "./TodoCheckbox";
import Button from "./Button";

const Todo = ({ toggleTodo, deleteTodo, id, completed, title }) => {
  let navigate = useNavigate()

  const handleDelete = (e) => {
    e.stopPropagation();
    deleteTodo(id);
  };

  const handleOnClick = (e) => { 
    navigate(`/todo/${id}`);  
  }

  return (
    <StyledDiv onClick={handleOnClick}>
      <TodoCheckbox toggleTodo={toggleTodo} completed={completed} id={id} />
      <h3>{title}</h3>
      <Button onClick={handleDelete} bgColor="#ef4444">
        Delete
      </Button>
    </StyledDiv>
  );
};
const StyledDiv = styled.div`
  display: flex;
  align-items: center;
  border-radius: 0.5rem;
  background-color: #1e293b;
  gap: 1rem;
  padding: 0.5rem 1rem;
  justify-content: space-between;
`;

export default Todo;

// apps/svelte-spa-router-app/src/components/Todo.svelte
<script>
  import { push } from "svelte-spa-router";
  import TodoCheckbox from "./TodoCheckbox.svelte";
  import Button from "./Button.svelte";
  import { todos } from "../stores";
  export let id;
  export let title;
  export let completed;

  const handleChange = (e) => {
    todos.toggle(id)
  }

  const handleOnDeleteClick = (e) => {
    todos.remove(id);
  }

  const handleClick = (e) => {
    push(`/todo/${id}`);
  }

</script>

<div on:click={handleClick}>
  <TodoCheckbox on:change={handleChange} completed={completed} />
  <h3>{title}</h3>
  <Button on:click={handleOnDeleteClick} --bg-color="#ef4444">Delete</Button>
</div>

<style>
  div {
    display: flex;
    align-items: center;
    border-radius: 0.5rem;
    background-color: #1e293b;
    gap: 1rem;
    padding: 0.5rem 1rem;
    justify-content: space-between;
  }
</style>
