// apps/svelte-spa-router-app/src/components/Button.svelte
<script>
</script>

<button on:click|preventDefault>
    <slot></slot>
</button>

<style>
  button {
    background-color: var(--bg-color);
    font-weight: bold;
    font-size: 1.175rem;
    padding: 0.5rem 1rem;
    color: #f8fafc;
    border: none;
    border-radius: .5rem;
    cursor: pointer;
    box-shadow: 1px 2px 3px rgba(0,0,0,0,.2);
  }
</style>

// apps/react-todo/src/lib/components/Button.jsx
import React from "react";
import styled from "styled-components";

const Button = ({ onClick, bgColor, children, ...rest }) => {
  return (
    <StyledButton bgColor={bgColor} onClick={onClick} {...rest}>
      {children}
    </StyledButton>
  );
};

const StyledButton = styled.button`
  background-color: ${(props) => props.bgColor || "#22c55e"};
  font-weight: bold;
  font-size: 1.175rem;
  padding: 0.5rem 1rem;
  color: #f8fafc;
  border: none;
  border-radius: 0.5rem;
  cursor: pointer;
  box-shadow: 1px 2px 3px rgba(0, 0, 0, 0, 0.2);
`;

export default Button;
